#!/usr/bin/env ruby
ENV['BUNDLE_GEMFILE'] = File.expand_path('../../Gemfile', __FILE__) # edit matching your Gemfile path
require File.expand_path('../../config/application', __FILE__)
require 'forever'

Forever.run :fork => true do
  filename = 'foreverb-cron'
  if file=~/wwwnewtone/
    deploy_dir = '/home/wwwnewtone/newtone.name'
    puts "Foreverb deploy directory: #{deploy_dir}"
    dir "#{deploy_dir}/current/"
    file "#{deploy_dir}/current/script/#{filename}"
    log  "#{deploy_dir}/shared/log/#{filename}.log"
    pid "#{deploy_dir}/shared/pids/#{filename}.pid"
  else
    pid "tmp/pids/#{filename}.pid"
  end

  on_error do |e|
    puts "Boom raised: #{e.message}"
    Airbrake.notify(e)
  end

  before :each do
    require File.expand_path('../../config/environment', __FILE__)
  end

  every 1.day do
    Parser.merge_artists_from_lastfm_chart_top_artist
  end

  every 1.day do
    Parser.merge_artists_from_lastfm_chart_top_tracks
  end

  every 1.day do
    Solr.optimize
  end

end
